# Generated by Django 5.1.2 on 2024-10-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('route_type', models.CharField(choices=[('PAVEMENT', 'Pavimento'), ('POTHOLES', 'Pavimento con Baches'), ('DIRT', 'Camino de Tierra'), ('TRAIL', 'Sendero')], max_length=10)),
            ],
        ),
    ]
