# Generated by Django 5.1.2 on 2024-10-30 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('BUS', 'Bus'), ('TRUCK', 'Camión'), ('CAR', 'Automóvil'), ('SUV', 'SUV')], max_length=5)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route')),
            ],
        ),
    ]
