# Generated by Django 5.1.2 on 2024-10-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_plate', models.CharField(max_length=10)),
                ('route_name', models.CharField(max_length=100)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
